[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn main:app"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[deploy.envs]
PYTHON_VERSION = "3.11"
